name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment variables
      run: echo "IMAGE_TAG=library:$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name library ${{ env.IMAGE_TAG }}

    - name: Execute client.py script in container
      run: docker exec library python tests

    - name: Stop and remove container
      run: |
        docker stop library
        docker rm library


